devise-security/devise-security

- devise-security.gemspec
- test/test_password_expired_controller.rb
SEED=59950 m test/test_password_expired_controller.rb:16
https://travis-ci.org/devise-security/devise-security/jobs/311606291
> Fix for flapping passwords expired spec

- .codeclimate.yml
- devise-security.gemspec
- lib/devise-security/version.rb
We were already using this in Gemfile.lock
> Use latest rubocop on both gemspec and CC

- config/locales/ja.yml
- lib/generators/devise_security/install_generator.rb
- test/test_install_generator.rb
Dear maintainers,
I'd like you to add Japanese locale to your great work.
> Add japanese locale

- config/locales/fr.yml
Hi I'm french and some of the wording really doesn't make sense and some words don't even exist so I polished it a bit
> Update french locale

- .travis.yml
- Appraisals
- Gemfile
- app/views/devise/paranoid_verification_code/show.html.erb
- app/views/devise/password_expired/show.html.erb
- devise-security.gemspec
- gemfiles/rails_5.0_stable.gemfile
- gemfiles/rails_5.1_stable.gemfile
- gemfiles/rails_5.2_stable.gemfile
- gemfiles/rails_6.0.gemfile
- lib/devise-security/models/database_authenticatable_patch.rb
- lib/devise-security/models/expirable.rb
- test/dummy/config/environments/test.rb
Minor adjustments to build to support Rails 6.
Fixes a couple of minor deprecations.
> Rails 6 support

- .travis.yml
- Appraisals
- Gemfile
- README.md
- devise-security.gemspec
- gemfiles/rails_4.2_stable.gemfile
- gemfiles/rails_5.0_stable.gemfile
- gemfiles/rails_5.1_stable.gemfile
- gemfiles/rails_5.2_stable.gemfile
- gemfiles/rails_6.0_beta.gemfile
Follow up to https://github.com/devise-security/devise-security/pull/80
> Add installation of imagemagick to CI so that rmagick can be unlocked

- config/locales/de.yml
Fixed grammer, spelling, removed shouting.
> Updated German translation

- Appraisals
> Bump Rails 6 to beta3

- README.md
- Rakefile
- lib/devise-security/models/mongoid/old_password.rb
- lib/devise-security/schema.rb
- lib/devise-security/version.rb
- test/dummy/db/migrate/20120508165529_create_tables.rb
> Issue 93 mongoid index

- lib/devise-security/version.rb
Bump version for release 0.14.0
> Release 0.14.0

- lib/devise-security.rb
- test/dummy/config/application.rb
- test/test_helper.rb
> Default DEVISE_ORM to :active_record

- lib/devise-security/version.rb
Bump gem version for release (see milestone 0.14.1 for contents).
> Release 0.14.1

- lib/devise-security/models/compatibility.rb
- lib/devise-security/models/compatibility/active_record_patch.rb
- lib/devise-security/models/compatibility/mongoid_patch.rb
- test/dummy/app/models/user.rb
- test/test_compatibility.rb
- test/test_sanity.rb
Some quick specs to demonstrate the issue reported in #103
> Fix namespace resolution problems for compatibility modules

- lib/devise-security/version.rb
Bump version in preparation for bugfix release.
> Bump gem version for release (0.14.2)

- app/views/devise/paranoid_verification_code/show.html.erb
- app/views/devise/password_expired/show.html.erb
- config/locales/en.yml
Only moving the harded translation from the views to the translation file.
> View translations

- config/locales/de.yml
In #115 translations where added and not specified in de.yml.
> Add missing german translations

- lib/devise-security/models/password_expirable.rb
Fix attribute_changed? deprecation warning
> Fix attribute_changed? deprecation warning

- Appraisals
- Gemfile
- Gemfile.lock
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- gemfiles/rails_5.1.gemfile
- gemfiles/rails_5.2.gemfile
- gemfiles/rails_6.0.gemfile
- lib/devise-security/controllers/helpers.rb
Co-authored-by: Troy Rosenberg <tmr08c@gmail.com>
> Add minitest-rails in preparation for improving tests

- config/locales/nl.yml
- lib/generators/devise_security/install_generator.rb
- test/test_install_generator.rb
Add Dutch (NL) locale.
Instead of only having this in my local app I thought it would be nice to add this to Devise-security itself.
> Add Dutch (NL) locale

- Gemfile
- lib/devise-security/controllers/helpers.rb
This just reformats some files and will help cleanup other PRs.
Co-authored-by: Troy Rosenberg <tmr08c@gmail.com>
> Formatting of helpers.rb and Gemfile

- .github/workflows/test_suite.yml
Closes https://github.com/devise-security/devise-security/issues/292
> Run tests on latest version of Ruby

- lib/devise-security/models/password_archivable.rb
Hi
This is a small pull request to fix a grammer in a code comment.
Please check it out. Thanks!
> Fix a grammer in a code comment
