lib/devise-security/controllers/helpers.rb, lib/devise-security/models/password_archivable.rb, lib/devise-security/models/password_expirable.rb, lib/devise-security/models/secure_validatable.rb, lib/devise-security/patches/confirmations_controller_captcha.rb, lib/devise-security/patches/confirmations_controller_security_question.rb, lib/devise-security/patches/passwords_controller_captcha.rb, lib/devise-security/patches/passwords_controller_security_question.rb, lib/devise-security/patches/registrations_controller_captcha.rb, lib/devise-security/patches/sessions_controller_captcha.rb, lib/devise-security/patches/unlocks_controller_captcha.rb, lib/devise-security/patches/unlocks_controller_security_question.rb
This removes the inconsistency within the code base of using low priority boolean operators (`and`, `or`, `not`) interchangeably with high priority boolean operators (`&&`, `||`, `!`) by favoring the high priority operators.
There were also a few operators missing in comparisons in `lib/devise-security/patches/passwords_controller_security_question.rb` and `lib/devise-security/patches/unlocks_controller_security_question.rb`.
This was described in forgotten PR [!214](https://github.com/phatworx/devise_security_extension/pull/214) in the original gem. Shoutout to @HenryKeiter for doing the legwork on this one.
=> Favor high priority boolean operators

lib/devise-security/controllers/helpers.rb, lib/devise-security/patches/confirmations_controller_captcha.rb, lib/devise-security/patches/controller_captcha.rb, lib/devise-security/patches/passwords_controller_captcha.rb, lib/devise-security/patches/registrations_controller_captcha.rb, lib/devise-security/patches/sessions_controller_captcha.rb, lib/devise-security/patches/unlocks_controller_captcha.rb, lib/devise-security/patches/unlocks_controller_security_question.rb
This changes the conditionals is the `*_controller_captcha.rb`s to remove some of the duplication of checking if the captcha is defined and valid. It makes the controllers a bit more readable.
This can also be applied to checking if the security question is defined and correct in the `*_controller_security_question.rb`s.
=> Refactor captcha validation to remove verbose conditionals

devise-security.gemspec
bypass_sign_in wasn't added until the 4.2.0 release.
=> Updated minimum devise version.

lib/devise-security/controllers/helpers.rb, lib/devise-security/patches/confirmations_controller_security_question.rb, lib/devise-security/patches/controller_security_question.rb, lib/devise-security/patches/passwords_controller_security_question.rb, lib/devise-security/patches/unlocks_controller_security_question.rb
Similar to an [earlier PR](https://github.com/devise-security/devise-security/pull/6) on the same subject.
This removes the duplicated checking of the security question's answer. In 3 places, it combines the checking for valid captchas and correct security question answer into a single method check to a new helper method. I think it improves readability a bit.
(This also adds the `valid_captcha_if_defined?` check in 2 places I missed in the earlier PR :see_no_evil: )
=> Remove compound conditionals

README.md
We need to add password_salt on migration because we get an error if we don't include this column.
=> Update Password Archivable to use password_salt

lib/devise-security/models/password_archivable.rb, test/dummy/db/migrate/20120508165529_create_tables.rb, test/test_password_archivable.rb
Although by default, Devise [generates](https://github.com/plataformatec/devise/blob/master/lib/generators/active_record/devise_generator.rb) migrations for an `encrypted_password` column that is `NOT NULL`, there are situations in which the column _is_ `NULL`. For instance, the documentation in the `devise_invitable` gem [explicitly requires](https://github.com/scambra/devise_invitable#activerecord-migration) developers using their gem to make that column `NULL`.
So, it's not safe to assume `encrypted_password` is always `NOT NULL`. In the use case where a user is created without a password, and then chooses one, a crash will be caused because `PasswordArchivable` attempts to create an `OldPassword` record with a null `encrypted_password`.
The changes in this PR simply make …
=> Avoid crash if resource model's encrypted_password column is NULL

devise-security.gemspec, test/test_helper.rb
Add filters to exclude certain folders and files from test coverage.
=> Coveralls filters

config/locales/tr.yml, lib/generators/devise_security/install_generator.rb, test/test_install_generator.rb
I was not able to run the tests. 😞
=> Added Turkish locale

lib/generators/templates/devise-security.rb
Hi!
I think that my change regarding the `deny_old_passwords` configuration paramenter can help other people when configuring this gem.
A member of my team got confused with the old documentation and though that the value should be a `:count` symbol and not the number of old passwords to be tested :P .
=> Documentation for initializer config file improved

.travis.yml, Appraisals, Gemfile, gemfiles/rails_4.2_stable.gemfile, gemfiles/rails_5.0_stable.gemfile, gemfiles/rails_5.1_stable.gemfile, gemfiles/rails_5.2_stable.gemfile, gemfiles/rails_6.0_beta.gemfile
rmagick released a new version recently that fails to install on travis.  This branch pins to a lower version until that can be resolved.
I also cleaned up the travis configs a bit so that it does not perform unnecessary builds.
=> pin rmagick & adjust travis builds

lib/devise-security/models/session_limitable.rb, test/test_session_limitable.rb
Models loading session limitable, but not one of the other features that 
load the compatibility layer would have missing methods becuase the ORM 
compatibility methods were not loaded.
Fixes #106
=> Load Compatibility when using session limitable

config/locales/ja.yml
Hi, I found a typo in `invalid_security_question` and fixed it.
=> Fix typo in ja locale

config/locales/de.yml
Use a german translation that fits better.
You can translate "Satzzeichen" with punctuation. Common use in german is "Sonderzeichen" in case of passwords.
=> Use better german translation for symbol

.travis.yml
While investigating random CI failures for this project, I noticed that this proejct is tested on Ruby 2.7.1 with Rails < 6, which is officially unsupported  (rails/rails#38426).
I think we should still add these version combinations to Travis CI's allow failures list, and hope this can make CI more stable.
=> Allow random failures for unsupported Ruby/Rails pairs

devise-security.gemspec
I'm working on docker optimisations for our app and trying to reduce the size of the gems we are using. Gem does not need to contain all of the files, so I reduced it. `test` folder is more than half of the whole gem.
=> Reduce gem size

Gemfile.lock, devise-security.gemspec
Devise 4.7.3 has a soft-lock of using 1.x
See https://github.com/devise-security/devise-security/issues/267
=> Lock omniauth to < 2.0.0

.github/workflows/test_suite.yml
Closes https://github.com/devise-security/devise-security/issues/344
Looks like mongoid and ruby-head aren't cooperating. Made https://github.com/devise-security/devise-security/issues/347 to address this later.
Not only does this clean up the config file, but the tests doesn't even get queued up on Github. This is vastly better than the previous approach, which queued up the jobs and they just completed really quickly.
=> Disable mongoid on ruby head

lib/devise-security/models/secure_validatable.rb, lib/devise-security/validators/password_complexity_validator.rb, test/test_complexity_validator.rb, test/test_secure_validatable.rb
Changes to `secure_validatable` were copied directly from the devise
`validatable` module.
Closes https://github.com/devise-security/devise-security/issues/322
=> Only show 'blank' error if password is missing

README.md, lib/generators/templates/devise_security.rb
- Add paranoid verfication config for devise_security.rb
- because there was no description about paranoid_code_regenerate_after_attempt in devise_security.rb.
- This is my first time to make a pull request, so I would appreciate it if you could point out any missing items.
=> Add paranoid verfication config for devise_security.rb

app/controllers/devise/password_expired_controller.rb, test/controllers/test_password_expired_controller.rb, test/dummy/app/controllers/overrides/password_expired_controller.rb
Currently if password is failed to update, nothing is displayed, and there is no way to change it easily (ie. without completely overriding `update` action in app's controller)
Devise though, allows user to add additional logic by passing a block to the `update`, like here: https://github.com/heartcombo/devise/blob/8593801130f2df94a50863b5db535c272b00efe1/app/controllers/devise/passwords_controller.rb#L34-L37
In this PR we're using same pattern.
So now user can do something like this:
```ruby
class Users::PasswordExpiredController < Devise::PasswordExpiredController
def update
super do |resource|
flash[:error] = resource.errors.full_messages.first if resource.errors.any?
end
end
end
```
=> PasswordExpiredController: Accept block for update action

.github/workflows/test_suite.yml, Gemfile.lock, devise-security.gemspec, lib/devise-security/models/expirable.rb, lib/devise-security/models/paranoid_verification.rb, lib/devise-security/models/password_archivable.rb, lib/devise-security/models/password_expirable.rb, lib/devise-security/models/secure_validatable.rb, lib/devise-security/models/security_questionable.rb, lib/devise-security/models/session_limitable.rb, test/test_expirable.rb, test/test_paranoid_verification.rb, test/test_password_archivable.rb, test/test_password_expirable.rb, test/test_secure_validatable.rb, test/test_security_questionable.rb, test/test_session_limitable.rb
This PR adds `self.required_fields(Model)` methods to all the models. `Devise::Models.check_fields! Model` calls this method under the hood to verify if the devise model has required columns present or not.
fixes #436
=> Add `required_fields` models method

config/locales/ko.yml, lib/generators/devise_security/install_generator.rb, test/test_install_generator.rb
This PR adds support for the Korean language (ko) to the devise-security I18n configuration.
✅ Changes Included
- Translated authentication and password-related messages (e.g., invalid captcha, password expiration, security question)
- Added error messages related to password complexity (e.g., uppercase, digits, symbols) in Korean
- Ensured all keys are consistent with existing en.yml structure for compatibility
📌 Motivation
Adding Korean translation improves the accessibility and user experience for Korean-speaking users of the application.
📝 Notes
- Verified structure and key consistency with existing locales
- Safe to merge — no impact on other locale files or runtime behavior
=> Add Korean (ko) translations for devise-security I18n
